-- Custom SQL migration file, put your code below! --
INSERT INTO "tags_table" ("name") VALUES
    -- Styles
    ('Abstract'),
    ('Minimal'),
    ('Flat'),
    ('Gradient'),
    ('Geometric'),
    ('Patterns'),
    ('Textures'),
    ('Isometric'),
    ('Lowpoly'),
    ('Vector'),
    ('3D'),
    ('Digital-art'),
    ('Painting'),
    ('Line-art'),
    ('Retro'),
    ('Vintage'),
    ('Futuristic'),
    ('Cyberpunk'),
    ('Synthwave'),
    ('Pixel-art'),

    -- Themes & moods
    ('Dark'),
    ('Light'),
    ('Colorful'),
    ('Pastel'),
    ('Neon'),
    ('Monochrome'),
    ('Warm'),
    ('Cool'),
    ('Vibrant'),
    ('Muted'),
    ('High-contrast'),
    ('Soft'),
    ('Moody'),
    ('Dreamy'),
    ('Calm'),
    ('Energetic'),
    ('Minimal-dark'),
    ('Minimal-light'),
    ('Black-and-white'),

    -- Nature & landscapes
    ('Nature'),
    ('Landscape'),
    ('Mountains'),
    ('Forest'),
    ('Jungle'),
    ('Desert'),
    ('Ocean'),
    ('Beach'),
    ('Waterfall'),
    ('River'),
    ('Lake'),
    ('Sky'),
    ('Clouds'),
    ('Sunset'),
    ('Sunrise'),
    ('Space'),
    ('Galaxy'),
    ('Stars'),
    ('Moon'),
    ('Planets'),

    -- Animals
    ('Animals'),
    ('Cats'),
    ('Dogs'),
    ('Birds'),
    ('Fish'),
    ('Wildlife'),
    ('Insects'),
    ('Wolves'),
    ('Tigers'),
    ('Lions'),

    -- Architecture & cityscapes
    ('City'),
    ('Urban'),
    ('Buildings'),
    ('Skyscrapers'),
    ('Bridges'),
    ('Streets'),
    ('Night-city'),
    ('Aerial'),
    ('Landmarks'),
    ('Castles'),

    -- Tech & sci-fi
    ('Technology'),
    ('AI'),
    ('Robots'),
    ('Gaming'),
    ('Spacecraft'),
    ('Spaceships'),
    ('Sci-fi'),
    ('Futurism'),
    ('Holographic'),
    ('Circuit'),

    -- Misc / Creative
    ('Fantasy'),
    ('Mythical'),
    ('Dragons'),
    ('Anime'),
    ('Cartoon'),
    ('Superheroes'),
    ('Cars'),
    ('Motorcycles'),
    ('Sports'),
    ('Music')
ON CONFLICT ("name") DO NOTHING;
