-- Custom SQL migration file, put your code below! --

-- Insert default wallpaper tags (ignore duplicates if re-run)
INSERT INTO "tags_table" ("name") VALUES
    -- Styles
    ('abstract'),
    ('minimal'),
    ('flat'),
    ('gradient'),
    ('geometric'),
    ('patterns'),
    ('textures'),
    ('isometric'),
    ('lowpoly'),
    ('vector'),
    ('3d'),
    ('digital-art'),
    ('painting'),
    ('line-art'),
    ('retro'),
    ('vintage'),
    ('futuristic'),
    ('cyberpunk'),
    ('synthwave'),
    ('pixel-art'),

    -- Themes & moods
    ('dark'),
    ('light'),
    ('colorful'),
    ('pastel'),
    ('neon'),
    ('monochrome'),
    ('warm'),
    ('cool'),
    ('vibrant'),
    ('muted'),
    ('high-contrast'),
    ('soft'),
    ('moody'),
    ('dreamy'),
    ('calm'),
    ('energetic'),
    ('minimal-dark'),
    ('minimal-light'),
    ('black-and-white'),

    -- Nature & landscapes
    ('nature'),
    ('landscape'),
    ('mountains'),
    ('forest'),
    ('jungle'),
    ('desert'),
    ('ocean'),
    ('beach'),
    ('waterfall'),
    ('river'),
    ('lake'),
    ('sky'),
    ('clouds'),
    ('sunset'),
    ('sunrise'),
    ('space'),
    ('galaxy'),
    ('stars'),
    ('moon'),
    ('planets'),

    -- Animals
    ('animals'),
    ('cats'),
    ('dogs'),
    ('birds'),
    ('fish'),
    ('wildlife'),
    ('insects'),
    ('wolves'),
    ('tigers'),
    ('lions'),

    -- Architecture & cityscapes
    ('city'),
    ('urban'),
    ('buildings'),
    ('skyscrapers'),
    ('bridges'),
    ('streets'),
    ('night-city'),
    ('aerial'),
    ('landmarks'),
    ('castles'),

    -- Tech & sci-fi
    ('technology'),
    ('ai'),
    ('robots'),
    ('gaming'),
    ('spacecraft'),
    ('spaceships'),
    ('sci-fi'),
    ('futurism'),
    ('holographic'),
    ('circuit'),

    -- Misc / Creative
    ('fantasy'),
    ('mythical'),
    ('dragons'),
    ('anime'),
    ('cartoon'),
    ('superheroes'),
    ('cars'),
    ('motorcycles'),
    ('sports'),
    ('music')
ON CONFLICT ("name") DO NOTHING;
